version: '3.1'

services:
  app:
    image: bmordue/amzn-recs:42b1f10
    ports:
      - 3003:3000
    volumes:
      - ./amzn-recs:/temp
    secrets:
      - AMZN_ACCESS_KEY_ID
      - AMZN_ACCESS_KEY_SECRET
      - AMZN_ASSOCIATE_TAG
      - DB_USERNAME
      - DB_PASSWORD
    environment:
      - AMZN_SERVICE_HOST
      - DB_URL="graphdb"
      - PRICE_LOOKUP_ENDPOINT
      - AMZN_RECS_LOG_LEVEL
      - CRAWL_API_ENDPOINT
  graphdb:
    image: neo4j:3.4
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=none
#  dd-agent:

secrets:
  AMZN_ACCESS_KEY_ID:
    external: true
  AMZN_ACCESS_KEY_SECRET:
    external: true
  AMZN_ASSOCIATE_TAG:
    external: true
  DB_USERNAME:
    external: true
  DB_PASSWORD:
    external: true

