version: '3.1'

services:
  app:
    image: bmordue/amzn-recs:latest
#    image: node:8.10
#    command: node src/api/crawl.js
#    working_dir: /proj
    volumes:
#      - .:/proj
      - ./amzn-recs:/temp
    secrets:
      - AMZN_ACCESS_KEY_ID
      - AMZN_ACCESS_KEY_SECRET
      - AMZN_ASSOCIATE_TAG
    environment:
      - AMZN_SERVICE_HOST
      - DB_URL=bolt://graphdb
      - PRICE_LOOKUP_ENDPOINT=http://prices:3000/price
      - AMZN_RECS_LOG_LEVEL=DEBUG
      - CRAWL_API_ENDPOINT=http://localhost:3000/crawl
    networks:
      - default
      - monitoring
  graphdb:
    image: neo4j:3.5.3
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=none
    networks:
      - default
      - monitoring
  prices:
    image: bmordue/price-for-asin:latest
    networks:
      - default
      - monitoring

secrets:
  AMZN_ACCESS_KEY_ID:
    external: true
  AMZN_ACCESS_KEY_SECRET:
    external: true
  AMZN_ASSOCIATE_TAG:
    external: true

networks:
  monitoring:
    external: true
