version: 2
jobs:
  build:
    docker:
      - image: node:15
    steps:
      - checkout
      - run: npm install && npx tsc && npm test
      - store_test_results:
          path: ~/output/results_xunit.xml

