version: 2
jobs:
  build:
    docker:
    - image: node:8.10-alpine
    steps:
    - checkout
    - run: npm install
  test:
    docker:
      - image: node:8.10-alpine
    steps:
      - checkout
      - run: npm install && npm test
  coverage:
    docker:
      - image: node:8.10-alpine
    steps:
      - checkout
      - run: rm -rf coverage
      - run: npm install
      - run: ./node_modules/.bin/nyc --reporter=lcov --reporter=text-lcov npm test
  analyse:
    docker:
      - image: newtmitch/sonar-scanner:3.2.0-alpine
    steps:
      - checkout
      - run: sonar-scanner -Dsonar.login=$SONAR_LOGIN
