version: 2
jobs:
  test:
    docker:
      - image: node:8.10-alpine
    steps:
      - checkout
      - run: npm install && npm test
  coverage:
    docker:
      - image: node:8.10-alpine
    steps:
      - checkout
      - run: sh coverage.sh
  analyse:
    steps:
      - checkout
      - run: sh sonar.sh

